apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: devopsartifact.jio.com/jpf-dsp_docker_registry__dev__dcr/dataplatforms/argocd/solar-system:v9
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
      imagePullSecrets:
        - name: argocd-jfrog-secret
